### ISSUE TITLE
Set up SonarCloud

### ISSUE THREAD

**Issue by rpuncel** [borisborelly/michar#10]
This will give us features such as quality gates, a place to see all static analysis, code coverage, etc. in one place, and be super awesome.

@rpuncel can't do it because he is not an admin

1. Go to https://sonarcloud.io/login
2. Log in with GitHub
3. You can use the "+" in the upper right corner to add a project; it should be self explanatory from there

**Comment by borisborelly** [comment]
https://sonarcloud.io/project/overview?id=borisborelly_michar

**Comment by borisborelly** [comment]
I added exclusions for `./docs` and `./tests`
