### ISSUE TITLE
Install Slack app on this repo

### ISSUE THREAD

**Issue by rpuncel** [borisborelly/michar#8]
Apparently to get the good GitHub integration, @borisborelly  needs to install it. It says to use [this link.](https://slack.github.com/github/v2/install/6621465/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlnZ2VyX2lkIjoiNjUwNTkxMDA0MzM0Ni42NTA1ODk5ODkyODAyLjc2MWViNTk3YmU5MmY0ZTJiNTc3MGYwYTk5NWNiN2ZlIiwidGVhbUlkIjoiVDA2RVZTRlM4UEwiLCJjbGllbnREb21haW4iOiJtaWNoYXJpbmR1c3RyaWVzbHRkIiwidXNlcklkIjoiVTA2RVlBQ0haREoiLCJjaGFubmVsSWQiOiJEMDZFU1VWSzk3RiIsInRyaWdnZXJpbmdBcHAiOiJBMDFCUDdSNEtOWSIsInJlcGxheUNvbW1hbmQiOnRydWUsImlhdCI6MTcwNTg2MzY2NCwiZXhwIjoxNzA1ODY3MjY0fQ.USYG9oO0YnUFPoRjxzyD83_ubyiKHF1jP_1Fsp6M4ZI)

**Comment by borisborelly** [comment]
done
